# Generated by Django 3.2.13 on 2022-05-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
