# Generated by Django 3.2.13 on 2022-05-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_userprofile_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
